// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ShieldVSExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "311f3401-ccf0-489a-b402-97528dc6b439";
        public static Guid guidPackage = new Guid(guidPackageString);

        public const string guidShieldVSExtensionPackageCmdSetString = "ebf96a3a-1e33-42f6-b931-bd933ad6baba";
        public static Guid guidShieldVSExtensionPackageCmdSet = new Guid(guidShieldVSExtensionPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int EnableId = 0x0200;
        public const int ConfigurationId = 0x0100;
    }
}